### ISSUE TITLE
lockwatch crashes to safemode 

### ISSUE THREAD

**Issue by vpww** [SniperGER/LockWatch#3]
just updated lockwatch to latest version (previously i used a version without activity face and it worked).
so after installation a respring springboard crashes into safemode. helps only deleting tweak
so i have it on i7 10.1.1

but it works great on ipad mini 4 10.3.3
probably it's just because activity

crashlogs attached

[crashlogs.zip](https://github.com/SniperGER/LockWatch/files/1734595/crashlogs.zip)

**Comment by SniperGER** [comment]
According to the crash log, it's not related to the Activity faces. It crashes, because it can't set the corner radius on some blurred views (the method doesn't exist in 10.1.1). As this method exists in 10.2 and above, it doesn't crash.

I'll work on a fix right away.

**Comment by SniperGER** [comment]
Should be fixed with e4a6420, latest version is available on the repo.
