### ISSUE TITLE
healthdata part 2

### ISSUE THREAD

**Issue by vpww** [SniperGER/LockWatch#4]
here it is:
https://www.dropbox.com/s/ncrftvbep8aqrli/healthdb_secure.sqlite?dl=0

**Comment by SniperGER** [comment]
Thank you very much! Even though the part of the database I needed (activity_caches) was completely empty, the structure was exactly the same as on iOS 11.

Just a quick tip: you could have added the file to your last issue and reopened it (though I'm not quite sure about the latter, I don't deal with GitHub issues this much)
