### ISSUE TITLE
Cannot change watch faces by long pressing or emulating force touch (Peek-a-Boo)

### ISSUE THREAD

**Issue by mmshivesh** [SniperGER/LockWatch#5]
iPhone 5s, 10.3.3, g0blin Jailbreak.
Cannot enter into watch face choose mode either using faux 3D Touch (Peek-a-Boo) nor by using a long press (after disabling Peek-a-Boo). Only way to change the watch face is using the enabled watch faces in settings and disabling everything except the one face that is needed.

**Comment by SniperGER** [comment]
Does it work with Peek-a-Boo not being installed at all?

Wish I could be testing this myself, but Peek-a-Boo doesn't seem to be working at all on iPad.

**Comment by SniperGER** [comment]
Closed due to inactivity (and because I can't recreate this).
