### ISSUE TITLE
Static Clock when opened with Flip Cover

### ISSUE THREAD

**Issue by abdelrahmanbahaa** [SniperGER/LockWatch#6]
iPad 4, IOS 10.3.3. Just shows a static clock (10:10) when iPad is opened automatically with Flip Cover.

**Comment by SniperGER** [comment]
f5c66ae should fix this. Compiled package will be uploaded to the repo shortly.

**Comment by SniperGER** [comment]
Well, leaving Customization is blocked by the passcode entry screen. I need to fix that first before releasing the update.

**Comment by SniperGER** [comment]
Build `18w12a.lw-release.180320` is now available on FESTIVAL repo (https://repo.festival.ml). I'm closing this issue as this build is supposed to fix it. If not, feel free to reopen it.
